# Generated by Django 4.2.7 on 2023-12-04 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("adress", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_make", models.CharField(max_length=255)),
                ("car_model", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("registration", models.CharField(max_length=255)),
                ("fuel", models.DateField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cars.owner"
                    ),
                ),
            ],
            options={
                "ordering": ["car_make", "car_model"],
            },
        ),
    ]
