# Generated by Django 4.2.7 on 2023-12-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="fuel",
            field=models.CharField(
                choices=[("E", "Electric"), ("G", "Gas"), ("D", "Diesel")],
                default="D",
                max_length=1,
            ),
        ),
    ]
