# Generated by Django 4.2.7 on 2023-12-04 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("genericRentalApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renteditem",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
    ]
