# Generated by Django 4.2.7 on 2023-12-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genericRentalApp", "0003_alter_renteditem_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="rental",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="rental",
            name="placed_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
